version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o bootstrap ./cmd/scraper/
      - zip deployment.zip bootstrap

artifacts:
  files:
    - deployment.zip
